server:
  port: ${PORT:8080}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

quotes_url: http://localhost:8083     
reference_url: http://localhost:8085

read_timeout: ${READ_TIMEOUT:10000}
write_timeout: ${WRITE_TIMEOUT:10000}