apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    # healthcheck
    run.googleapis.com/launch-stage: ALPHA
    client.knative.dev/user-image: gcr.io/dan-workshop-project-332213/quotes-jvm
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-central1
  name: quotes
  namespace: '161275344265'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        client.knative.dev/user-image: gcr.io/dan-workshop-project-332213/quotes-jvm
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 386.0.0
        run.googleapis.com/cloudsql-instances: dan-workshop-project-332213:us-central1:quote-cr-db-instance
        run.googleapis.com/vpc-access-connector: quote-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: INSTANCE_CONNECTION_NAME
          value: quote-cr-db-instance
        - name: DB_NAME
          value: quote_db
        - name: DB_USER
          value: quote_user
        - name: DB_PASS
          value: quote-cr-db-pwd
        - name: INSTANCE_HOST
          value: 172.24.0.10
        - name: DB_HOST
          value: 172.24.0.10
        - name: DB_PORT
          value: '5432'
        - name: SERVER.PORT
          value: '8080'
        - name: SPRING_PROFILES_ACTIVE
          value: cloud-dev
        image: gcr.io/dan-workshop-project-332213/quotes-jvm
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
      serviceAccountName: cr-quote-service-account
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
