apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:    
    # healthcheck
    run.googleapis.com/launch-stage: ALPHA
    client.knative.dev/user-image: gcr.io/dan-workshop-project-332213/bff-jvm
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-central1
  name: bff-dont
  namespace: '161275344265'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        client.knative.dev/user-image: gcr.io/dan-workshop-project-332213/bff-jvm
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 386.0.0
        autoscaling.knative.dev/minScale: '0'
        # run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 20
      containers:
      - env:
        - name: SERVER.PORT
          value: '8080'
        - name: QUOTES_URL
          value: https://quotes-dont-ieuwkt6jkq-uc.a.run.app
        - name: REFERENCE_URL
          value: https://reference-dont-ieuwkt6jkq-uc.a.run.app
        - name: READ_TIMEOUT
          value: '10000'
        - name: WRITE_TIMEOUT
          value: '10000'
        image: gcr.io/dan-workshop-project-332213/bff-jvm
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
        # startupProbe:
        #   httpGet:
        #     path: /actuator/startup
        #   # initialDelaySeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
      serviceAccountName: 161275344265-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
