apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    # healthcheck
    run.googleapis.com/launch-stage: ALPHA
    client.knative.dev/user-image: gcr.io/dan-workshop-project-332213/quotes-jvm
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-central1
  name: quotes-dont
  namespace: '161275344265'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        client.knative.dev/user-image: gcr.io/dan-workshop-project-332213/quotes-jvm
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: dan-workshop-project-332213:us-central1:quote-cr-db-instance
        run.googleapis.com/vpc-access-connector: projects/dan-workshop-project-332213/locations/us-central1/connectors/quote-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        # autoscaling.knative.dev/minScale: '1'
    spec:
      containerConcurrency: 20
      containers:
      - env:
        - name: INSTANCE_CONNECTION_NAME
          value: quote-cr-db-instance
        - name: DB_NAME
          value: quote_db
        - name: DB_USER
          value: quote_user
        - name: DB_PASS
          value: quote-cr-db-pwd
        - name: INSTANCE_HOST
          value: 172.24.0.10
        - name: DB_HOST
          value: 172.24.0.10
        - name: DB_PORT
          value: '5432'
        - name: SERVER.PORT
          value: '8080'
        - name: SPRING_PROFILES_ACTIVE
          value: cloud-prod
        - name: TARGET
          value: Cloud Run - Postgres 14 - Java 17
        image: gcr.io/dan-workshop-project-332213/quotes-jvm
        ports:
        - containerPort: 8080
          name: http1
        # startupProbe:
        #   httpGet:
        #     path: /actuator/startup
          # failureThreshold: 30 
          # periodSeconds: 10 
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
      serviceAccountName: 161275344265-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
