apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    # healthcheck
    run.googleapis.com/launch-stage: ALPHA
    client.knative.dev/user-image: gcr.io/dan-workshop-project-332213/reference-jvm
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-central1
  name: reference
  namespace: '161275344265'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        client.knative.dev/user-image: gcr.io/dan-workshop-project-332213/reference-jvm
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 386.0.0
        # run.googleapis.com/cpu-throttling: 'true'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: SERVER.PORT
          value: '8080'
        - name: DELAY
          value: '1'
        image: gcr.io/dan-workshop-project-332213/reference-jvm
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
        startupProbe:
          httpGet:
            path: /actuator/startup
          # failureThreshold: 30 
          # periodSeconds: 10 
        livenessProbe:
          httpGet:
            path: /actuator/health
      serviceAccountName: cr-reference-service-account
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
